### ISSUE TITLE
不支持linux

### ISSUE THREAD

**Issue by fanTMT** [Stardawn0v0/PyQtScrcpy#2]
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306

**Comment by Stardawn0v0** [comment]
感谢反馈，但看起来是pywin32库的问题，我没有实体Linux系统无法测试，有空会修一下



| |
Stardawn
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月10日 17:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Stardawn0v0/PyQtScrcpy] 不支持linux (Issue #2) |

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306

**Comment by fanTMT** [comment]
![image](https://github.com/Stardawn0v0/PyQtScrcpy/assets/168617941/8d010acb-81f1-4510-a165-f1e19340ced1)
界面没有问题！但是不能运行

**Comment by ctr54188** [comment]
> ![image](https://private-user-images.githubusercontent.com/168617941/347344967-8d010acb-81f1-4510-a165-f1e19340ced1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjIyMjAsIm5iZiI6MTcyMDYyMTkyMCwicGF0aCI6Ii8xNjg2MTc5NDEvMzQ3MzQ0OTY3LThkMDEwYWNiLTgxZjEtNDUxMC1hMTY1LWYxZTE5MzQwY2VkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNDMyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzZhM2NmZjE5Njc2ZWExODI0OTQ0ZTg4NTM5ZTRhM2YyZDFmZDY0MmM5Y2ZhMzM3NDdiNjI2MmZkMDg3N2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tjT2yfJ31CxKbDGYLkxoJPcVGIs31qZkmNMtW0WxGEs) 界面没有问题！但是不能运行

试了下，要把所有的带CREATE_NO_WINDOW的注释掉，main.py的185行注释掉，然后util.py里的21  34  65  91删掉creationflags=subprocess.CREATE_NEW_CONSOLE这个参数，这样可以读到usb列表，但是我还是点设备号或者点启动时报了读取屏幕id列表失败，估计是要先装scrcpy
<img width="834" alt="image" src="https://github.com/Stardawn0v0/PyQtScrcpy/assets/26321252/688bfae6-130b-46ea-bae0-917dca7a19f4">

**Comment by ctr54188** [comment]
@fanTMT 改完了，刚才写的main.py里的185行不能删，要把里面的, creationflags=subprocess.CREATE_NEW_CONSOLE, 删掉
另外184行改一下  cmd = SCRCPY + ' ' + ' '.join(args)
还有要homebrew 安装scrcpy 和adb
brew install --cask android-platform-tools
brew install scrcpy
consts.py里的adb和scrcpy路径换成homebrew里的路径    
ADB = os.path.join(BASEDIR, 'adb')
SCRCPY = os.path.join('/opt/homebrew/bin', 'scrcpy')
<img width="1214" alt="image" src="https://github.com/Stardawn0v0/PyQtScrcpy/assets/26321252/ae2b1d71-a7cb-4bf8-afaa-4c98ec69a530">

**Comment by fanTMT** [comment]
那我建议使用 platform.platform() 判断系统版本 全平台化！

**Comment by fanTMT** [comment]
util.py里的21 34 65 91删掉creationflags=subprocess.CREATE_NEW_CONSOLE这个参数
linux 配置 consts.py里的adb和scrcpy路径
ADB = 'adb'
SCRCPY = 'scrcpy'
main.py里的185行creationflags=subprocess.CREATE_NEW_CONSOLE, 删掉
184行改成 cmd = SCRCPY + ' ' + ' '.join(args)
可以使用
