### ISSUE TITLE
GPL-3.0 License 与 “禁止商用” 不兼容

### ISSUE THREAD

**Issue by changhexiong** [Stardawn0v0/PyQtScrcpy#3]
虽然大家都知道许可证现实里毫无软用，但是太明显的问题最好不要有

GPL-3.0 第二条中： This License explicitly affirms your unlimited permission to run the unmodified Program. 

不能一边GPL同时禁止商用

如果希望禁止商用同时个人可以使用和访问代码，可以考虑 CC BY-NC 4.0

**Comment by Stardawn0v0** [comment]
欸我刚发现那有句禁止商用，Copilot全责
已经删了
